name: Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tasks: [check, build, test:ci]

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: install bun
        uses: oven-sh/setup-bun@v2

      - name: install dependencies
        run: bun install --frozen-lockfile

      - run: bun run ${{ matrix.tasks }}
